# Generated by Django 3.2.4 on 2021-06-20 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutyDays',
            fields=[
                ('day', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('dayOfWeek', models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=80)),
                ('monthName', models.CharField(max_length=8)),
                ('monthNumber', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=20)),
                ('userFullname', models.CharField(max_length=60)),
                ('userId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('isOnDutyThisMonth', models.BooleanField(default=False)),
                ('userPhone', models.CharField(max_length=15)),
                ('userExt', models.CharField(max_length=10)),
                ('isOwner', models.BooleanField(default=False)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.group')),
            ],
        ),
        migrations.CreateModel(
            name='UsersDutyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDuty', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.dutydays')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.user')),
            ],
        ),
    ]
